CREATE TABLE activities (
  id SERIAL,
  block_height BIGINT,
  type ACTIVITY_TYPE NOT NULL,
  txid VARCHAR NULL,
  event_position INTEGER NULL,
  fee NUMERIC(20) NULL,
  inputs JSONB NULL,
  output_count INTEGER NULL,
  bonded NUMERIC(20) NULL,
  unbonded NUMERIC(20) NULL,
  unbonded_from BIGINT NULL,
  staking_account_address VARCHAR NULL,
  staking_account_nonce BIGINT NULL,
  joined_council_node_id BIGINT NULL,
  joined_council_node JSONB NULL,
  affected_council_node_id BIGINT NULL,
  affected_council_node JSONB NULL,
  jailed_until BIGINT NULL,
  punishment_kind PUNISHMENT_KIND NULL,
  PRIMARY KEY(id),
  UNIQUE(txid),
  UNIQUE(block_height, event_position),
  FOREIGN KEY(block_height) REFERENCES blocks(height),
  FOREIGN KEY(staking_account_address) REFERENCES staking_accounts(address)
);